name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        deno_version:
          - "2.x"
    runs-on: ${{ matrix.runner }}
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "${{ matrix.deno_version }}"
      - uses: actions/cache@v4
        with:
          key: deno-${{ hashFiles('**/*') }}
          restore-keys: deno-
          path: |
            /home/runner/.cache/deno/deps/https/deno.land
      - name: Lint check
        run: deno lint
      - name: Format check
        run: deno fmt --check
      - name: Type check
        run: deno task check

  jsr-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"
      - name: Publish (dry-run)
        run: |
          deno publish --dry-run
